#!/bin/bash
while read p; do
  echo "$p"
  test=$(fortune -s | toilet -f Fender.flf && cat bill-no-bg.txt)
  echo "$test" | convert -background black -fill white -font $p -trim label:@- temp/fonts/$p.png
done <fonts

#for f in /usr/share/figlet/* 
#do 
#  fs=$f
#  echo "fs: $fs"
#  fname=$(echo $fs | grep -o -P '(?<=/usr/share/figlet/).*(?=)')
#  echo "fname: $fname" >> test
#  toilet -f "$fname" "$fname" >> test
#  echo -e "\n\n\n\n\n\n" >> test
#done